### ISSUE TITLE
"Aw, Snap!" out of memory error.

### ISSUE THREAD

**Issue by OneOfMany07** [immortalityidle/immortalityidle.github.io#12]
Saw a recommendation to hit an achievement and while letting the process run in the background I returned to the Chrome error "Aw, Snap!" about out of memory.  I didn't see a way to gather extra information.  I'd guess 3-4 hours runtime max on a 4.4GHz 4790k CPU.

I took my in progress game and had only 1 task "Burning things" and set it on my fastest speed (3rd button).  I'd die over and over, and supposedly at 12k deaths I'd unlock something.  Basically it dies really quickly over and over.  Opening the page again after the crash I see just under 18k deaths (that many "lives").  I'd started at around 100.

Chrome "Version 103.0.5060.114 (Official Build) (64-bit)"

Wonder if a log grew too long?  Or?  I think I've run the game for longer than that, but without so many deaths.

**Comment by Hornsoup** [comment]
if (this.currentLog.length > 300){
        // peel off the oldest
        this.currentLog.splice(this.currentLog.length - 1, 1);
      }
It's probably not a log per above.
I'm not entirely sure how the Subject works on the backend since it's a module, but there's a lot of stuff subscribed for reincarnation so there's a lot of potential leaks. Though I say that, others have done the 15k deaths for lifespan but didn't run out of memory so there may be something else at work for you.

**Comment by immortalityidle** [comment]
How much RAM does your system have? and did you have any other chrome tabs/windows running?

**Comment by immortalityidle** [comment]
Closing this as a fixed. Hopefully it is.
